### ISSUE TITLE
postgres sql script fixes

### ISSUE THREAD

**Issue by jangorecki** [Roenbaeck/anchor#10]
@elari-ttu
Not sure if you are aware, but on my current psql

```
"PostgreSQL 9.3.6 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit"
```

I had to do find and replace:
- `varchar(max)` -> `varchar(4000)`
- `geography` -> `varchar(4000)`

in generated sql script to make it passing

**Comment by nathanclayton** [comment]
You may want to instead do

 * `varchar(max) -> varchar` or `varchar(max) -> text`
 * `geography -> point`

This is due to the fact that SQL server `varchar(max)` can go over 4k characters, similar to PostgreSQL `varchar` without size. Also, a `geography` column is roughly similar to the `point` data type (although you'd probably need to install PostGIS to get full GIS-compatible data types).

**Comment by jangorecki** [comment]
This is fine but I think it could be handled by sisulator automatically, without the `point` type which requires additional dependency.

**Comment by nathanclayton** [comment]
Point is a [built in](http://www.postgresql.org/docs/9.3/static/datatype-geometric.html#AEN6607) data type since at least 7.1. No additional dependencies needed. Now, if you intended to use the geometry data type, that's another thing entirely.

**Comment by jangorecki** [comment]
Then `point` seems to be perfect. I will try to run some more tests on postgres, do you have a data you are using for stress testing of different queries?

**Comment by delostilos** [comment]
The data type conversions between the different SQL dbmses are now handled in the DataTypeConverter module.
If there is something missing add your datatype conversions. Also the UI has some helper lists to get the correct data types.
